export class InputRouter {
  detectInputMode(input) {
    // Workflow execution mode
    if (input.workflowId && input.executionId && input.input) {
      return {
        mode: 'workflow',
        valid: true,
        data: {
          ...input,
          executionId: input.executionId || `exec_${Date.now()}`
        }
      };
    }
    
    // Replay mode
    if (input.executionId && input.replay) {
      return {
        mode: 'replay',
        valid: true,
        data: {
          ...input,
          executionId: input.executionId || `exec_${Date.now()}`
        }
      };
    }
    
    // API Step mode - detect by common API patterns
    if (input.type || input.requestId || input.payload || input.user) {
      const type = input.type || 'generic-api';
      return {
        mode: 'api',
        valid: true,
        data: this.mapApiToWorkflow(input, type)
      };
    }
    
    // Unknown format
    return {
      mode: 'unknown',
      valid: false,
      error: 'Invalid input format. Expected workflow execution, API request, or replay format.'
    };
  }
  
  mapApiToWorkflow(apiInput, type) {
    const executionId = `exec_${Date.now()}`;
    return {
      workflowId: `api::${type}`,
      executionId,
      input: this.normalizeApiInput(apiInput, type),
      autoGenerated: true,
      originalMode: 'api',
      rawInput: apiInput
    };
  }
  
  normalizeApiInput(apiInput, type) {
    // Normalize API input into Step-safe format
    switch (type) {
      case 'file-upload':
        return {
          fileId: apiInput.payload?.fileName || 'unknown',
          sizeMB: apiInput.payload?.fileSizeMB || 0,
          mimeType: apiInput.payload?.fileType || 'unknown',
          userId: apiInput.user?.id || 'anonymous',
          userRole: apiInput.user?.role || 'user',
          requestId: apiInput.requestId,
          type: apiInput.type,
          originalPayload: apiInput.payload
        };
      default:
        return {
          requestId: apiInput.requestId || `req_${Date.now()}`,
          type: apiInput.type || 'generic',
          userId: apiInput.user?.id || 'anonymous',
          data: apiInput.payload || apiInput,
          originalInput: apiInput
        };
    }
  }
  
  getSuccessMessage(mode, workflowId) {
    switch (mode) {
      case 'workflow':
        return `Workflow execution started: ${workflowId}`;
      case 'api':
        return `Input detected as API request. Auto-routing to ${workflowId} Step.`;
      case 'replay':
        return 'Replay mode activated.';
      default:
        return 'Execution started.';
    }
  }
  
  getErrorGuidance() {
    return {
      error: 'Invalid execution request.',
      guidance: 'Expected either:',
      formats: [
        {
          name: 'Workflow execution format',
          example: '{ "workflowId": "wf_name", "executionId": "exec_123", "input": {...} }'
        },
        {
          name: 'API Step input format', 
          example: '{ "type": "file-upload", "requestId": "req_001", "payload": {...} }'
        },
        {
          name: 'Replay format',
          example: '{ "executionId": "exec_123", "replay": true }'
        }
      ]
    };
  }
}

export const inputRouter = new InputRouter();
